apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter
spec:
  selector:
    matchLabels:
      app: jupyter
  replicas: 1
  template:
    metadata:
      labels:
        app: jupyter
    spec:
      containers:
      - name: notebook
        image: lukasheinrich/blackboxdriver
        imagePullPolicy: Always
        command:
        - jupyter
        - notebook
        - --allow-root
        - --ip
        - 0.0.0.0
        ports:
        - containerPort: 8888
      restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: notebook
spec:
  type: NodePort
  selector:
    app: jupyter
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8888
    nodePort: 31313

